# Generated by Django 4.2 on 2023-04-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_svg_link',
            field=models.URLField(default='https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU'),
        ),
    ]
