# Generated by Django 4.2 on 2023-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_source_source_svg_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='home_url',
            field=models.URLField(default='https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU'),
        ),
    ]
