# Generated by Django 4.2 on 2023-08-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='favi_link',
            field=models.URLField(default='https://ibb.co/n7bVQjR'),
        ),
    ]
