# Generated by Django 4.1.6 on 2023-04-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='last_name',
            new_name='source_url',
        ),
    ]
