# Generated by Django 4.2 on 2023-04-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='name',
            field=models.CharField(default='Online News', max_length=255),
        ),
    ]
