# Generated by Django 4.2 on 2023-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_category',
            field=models.CharField(default='News', max_length=200),
        ),
    ]
