# Generated by Django 4.2 on 2023-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_source_home_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='favi_link',
            field=models.URLField(default='https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU'),
        ),
    ]
