# Generated by Django 4.2 on 2023-07-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_news_favi_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='News', max_length=255),
        ),
    ]
