# Generated by Django 4.2 on 2023-07-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscribers_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
