# Generated by Django 4.2 on 2023-07-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_subscribers_news_clicks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
