# Generated by Django 4.2 on 2023-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_alter_news_favi_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='home_url',
            field=models.URLField(default='https://ibb.co/n7bVQjR'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_svg_link',
            field=models.URLField(default='https://ibb.co/n7bVQjR'),
        ),
    ]
